# How many blocks can be in each section.
MaxSectionSize: 28800

# How many blocks are analyzed in arena creation per second. Increasing
# this will increase the speed arenas are created but will cause more lag.
AnalyzeBlockSpeed: 49600

# The amount of blocks to reset per second. Normal is the default speed
# if none is specified when resetting an arena. Must be an integer
# (a whole number) above 20
Speeds:
  VerySlow: 200
  Slow: 1000
  Normal: 10000
  Fast: 40000
  VeryFast: 100000
  Extreme: 200000

# How often the game will update you on the reset progress of arenas.
# The interval is how long until it can update you again (in seconds),
# while the percentage is how much it must achieve since it last
# notified you before it can do so again.
ResetUpdate:
  Interval: 10
  Percent: 5

# If compression is somehow having issues, this will stop new arenas from being created compressed
# You can convert existing arenas by double clicking the plugin jar file (so this must be done on
# your PC)
DisableCompression: false

# The teleport command suggested to the user from clicking an arena in /arena list
# Variables: player, x, y, z, world
TeleportCommandSuggestion: '/tp <x> <y> <z>'

# If an arena is created in an old version and the plugin has not been updated yet, you
# can enable this to allow the arena to still load anyway.
IgnoreOutdatedMaterials: false
